### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by themowski** [Sequoia-Theme/vs-code#2]
Michael's name appears to be misspelled at the bottom of the README. It is also misspelled on the marketplace page for the extension (not sure if the marketplace just imports the README?): https://marketplace.visualstudio.com/items?itemName=wicked-labs.sequoia

![image](https://user-images.githubusercontent.com/13295249/176446673-95397dfc-e968-47c3-a43f-5f5eff9459ed.png)

**Comment by michael-andreuzza** [comment]
Can't even spell my own,I should quit.😁 Thank you so much.
