### ISSUE TITLE
Request: Italic support 

### ISSUE THREAD

**Issue by raygervais** [Sequoia-Theme/vs-code#5]
Hello! 

I love your themes and use Sequoria, [Serendipity](https://github.com/Serendipity-Theme/vs-code.git) and [Malibu](https://github.com/Malibu-Theme/vs-code.git) regularily, but I notice that there's never any support for italics in any of the themes. Is this by choice?

I know most themes these days for VS Code and similar include italics support, and I won't deny that I'm so used to it now that it seems odd to not see it in the expected places, hence I'm wondering how hard it would be to add support for italics similar to popular themes such as VS Code's Default Dark, Solarized Dark, and others have. 

Thanks! 

![image](https://github.com/Sequoia-Theme/vs-code/assets/14265337/1c5a17b8-ecca-4245-8bfe-30ecbabb0ef5)

![image](https://github.com/Sequoia-Theme/vs-code/assets/14265337/04d5dfa6-bd49-4621-bf3b-b822bda57d13)

![image](https://github.com/Sequoia-Theme/vs-code/assets/14265337/8e1705ad-4e0a-47e8-8dcb-40e28d97556a)

**Comment by michael-andreuzza** [comment]
The themes are using italics from scratch. All my themes. I use Malibu daily and i have no issues with italics, as you can see there is italics. I am using operator Mono.

Serendipity
![image](https://github.com/Sequoia-Theme/vs-code/assets/34077176/81f4af6e-8b4a-4483-9514-c91445e64e64)

sequoia
![image](https://github.com/Sequoia-Theme/vs-code/assets/34077176/fb22a1f2-3920-476f-8380-8a0c82fdf58f)


Malibu
![image](https://github.com/Sequoia-Theme/vs-code/assets/34077176/cc0a0fba-afad-4374-8c19-6c9edfbdccfc)
